services:
  pg:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: purchases_accounting
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d purchases_accounting" ]
      interval: 5s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_container
    depends_on:
      pg:
        condition: service_healthy
    env_file:
      - backend/.env.template
    ports:
      - "8000:8000"


volumes:
  postgres_data: