"""Create Payment table

Revision ID: e4564c26ed9c
Revises: 0f94bc7e13c3
Create Date: 2025-02-19 09:03:44.575382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4564c26ed9c"
down_revision: Union[str, None] = "0f94bc7e13c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("CASH", "CASHLESS", name="paymenttypeenum"),
            nullable=False,
        ),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["receipts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    # ### end Alembic commands ###
