"""Added column total to Reciepts Table

Revision ID: 640c1585914a
Revises: 0195fd936125
Create Date: 2025-02-20 08:59:49.217169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "640c1585914a"
down_revision: Union[str, None] = "0195fd936125"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipts", sa.Column("total", sa.DECIMAL(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("receipts", "total")
    # ### end Alembic commands ###
